language: python
python:
  - "3.6"

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

env:
  - KERAS_BACKEND="tensorflow"
  - KERAS_IMPLEMENTATION="tensorflow"

before_install:
  - pip install tensorflow tensorflow_probability keras
#  - pip install requests tempfile random
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ];
      then
        pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl
      fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ];
      then
        pip install https://github.com/ANTsX/ANTsPy/releases/download/Weekly/antspy-0.1.4-cp36-cp36m-macosx_10_7_x86_64.whl
      fi

install:
#  - python setup.py install

branches:
  only:
    - master
